version: "3"

services:
  ############################################### Zookeeper Cluster ###############################################

  zoo1:
    image: confluentinc/cp-zookeeper
    container_name: zoo1
    hostname: zoo1
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    # volumes: 
    #   - ./data/zookeeper/zoo1-data:/var/lib/zookeeper/data
    #   - ./data/zookeeper/zoo1-log:/var/lib/zookeeper/log

  zoo2:
    image: confluentinc/cp-zookeeper
    container_name: zoo2
    hostname: zoo2
    restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    # volumes: 
    #   - ./data/zookeeper/zoo2-data:/var/lib/zookeeper/data
    #   - ./data/zookeeper/zoo2-log:/var/lib/zookeeper/log

  zoo3:
    image: confluentinc/cp-zookeeper
    container_name: zoo3
    hostname: zoo3
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    # volumes: 
    #   - ./data/zookeeper/zoo3-data:/var/lib/zookeeper/data
    #   - ./data/zookeeper/zoo3-log:/var/lib/zookeeper/log




  ############################################### Kafka Cluster ###############################################

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://:19092,LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    # volumes:
    #   - ./data/kafka/kafka1:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka2
      - kafka3

  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://:19093,LISTENER_DOCKER_EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    # volumes:
    #   - ./data/kafka/kafka2:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3   

  kafka3:
    image: confluentinc/cp-kafka
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://:19094,LISTENER_DOCKER_EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    # volumes:
    #   - ./data/kafka/kafka3:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3  

  # schema-registry:
  #   image: confluentinc/cp-schema-registry
  #   container_name: schema-registry
  #   hostname: schema-registry
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:32181
  #     SCHEMA_REGISTRY_HOST_NAME: localhost
  #     SCHEMA_REGISTRY_LISTENERS: http://localhost:8081

  # connect:
  #   image: debezium/connect
  #   container_name: connect
  #   depends_on: 
  #     - BOOTSTRAP_SERVERS: kafka1:9092


  ############################################### NODEJS Server ###############################################

  nodeServer:
    image: 311200/kafka-poc01
    container_name: nodeServer
    hostname: nodeServer
    ports: 
      - 5000:5000
    environment: 
      BROKER_LIST: "kafka1:19092,kafka2:19093,kafka3:19094"
    depends_on: 
      - kafka1